import type {
  Activity,
  AuditEntry,
  CaptureEvent,
  Contact,
  DailyLog,
  DemoState,
  MessageThread,
  Notification,
  PhotoAsset,
  Project,
  RfiDraft,
  Rule,
  Task,
} from "@/lib/domain";

const policyMatrix = {
  homeowner: {
    progressPhotos: "Curated only",
    safetyAlerts: "Emergency only",
    costAlerts: "Approved changes",
    scheduleAlerts: "Milestones",
    clientFacingNotes: "Yes",
  },
  superintendent: {
    progressPhotos: "All relevant",
    safetyAlerts: "Yes",
    costAlerts: "Yes",
    scheduleAlerts: "Yes",
    clientFacingNotes: "Internal",
  },
  foreman: {
    progressPhotos: "Assigned scope",
    safetyAlerts: "Yes",
    costAlerts: "Limited",
    scheduleAlerts: "Daily work",
    clientFacingNotes: "Internal",
  },
  builder: {
    progressPhotos: "Summary + exceptions",
    safetyAlerts: "Yes",
    costAlerts: "Yes",
    scheduleAlerts: "Yes",
    clientFacingNotes: "Both",
  },
  supplier: {
    progressPhotos: "Delivery-related",
    safetyAlerts: "No",
    costAlerts: "POs",
    scheduleAlerts: "Delivery dates",
    clientFacingNotes: "No",
  },
  subcontractor: {
    progressPhotos: "Their scope",
    safetyAlerts: "Their violations",
    costAlerts: "Their contract",
    scheduleAlerts: "Their activities",
    clientFacingNotes: "No",
  },
  architect: {
    progressPhotos: "Design issues",
    safetyAlerts: "Relevant only",
    costAlerts: "Design impact",
    scheduleAlerts: "RFI deadlines",
    clientFacingNotes: "No",
  },
};

function makeActivities(prefix: string, items: Omit<Activity, "id">[]): Activity[] {
  return items.map((item, index) => ({
    ...item,
    id: `${prefix}-activity-${index + 1}`,
  }));
}

const projects: Project[] = [
  {
    id: "harbor-view",
    name: "115 Harbor View Drive",
    address: "115 Harbor View Drive, Lake Geneva, WI",
    projectType: "Custom home",
    homeownerName: "The Hendersons",
    lat: 42.5864,
    lng: -88.4367,
    phase: "Framing",
    percentComplete: 41,
    contractValue: 1825000,
    personaAccess: ["Foreman", "Superintendent", "Homeowner", "Office / PM"],
    milestones: [
      { id: "hv-ms-1", label: "Foundation complete", date: "2026-05-12", status: "done" },
      { id: "hv-ms-2", label: "Framing inspection", date: "2026-07-21", status: "current" },
      { id: "hv-ms-3", label: "MEP rough-in", date: "2026-08-10", status: "upcoming" },
      { id: "hv-ms-4", label: "Cabinet install", date: "2026-10-16", status: "upcoming" },
    ],
    activities: makeActivities("hv", [
      { label: "West wall framing", crew: "Framers", start: "2026-07-10", end: "2026-07-12", percentComplete: 100, dependencyIds: [], status: "complete" },
      { label: "Second-floor framing", crew: "Framers", start: "2026-07-11", end: "2026-07-17", percentComplete: 70, dependencyIds: ["hv-activity-1"], status: "active" },
      { label: "Window opening verification", crew: "Superintendent", start: "2026-07-12", end: "2026-07-12", percentComplete: 0, dependencyIds: ["hv-activity-2"], status: "at-risk" },
      { label: "Roof truss delivery", crew: "Supplier", start: "2026-07-13", end: "2026-07-13", percentComplete: 0, dependencyIds: [], status: "queued" },
      { label: "Roof framing", crew: "Framers", start: "2026-07-14", end: "2026-07-18", percentComplete: 0, dependencyIds: ["hv-activity-4"], status: "queued" },
      { label: "Weather barrier", crew: "Envelope", start: "2026-07-19", end: "2026-07-20", percentComplete: 0, dependencyIds: ["hv-activity-5"], status: "queued" },
      { label: "Framing inspection", crew: "Municipal", start: "2026-07-21", end: "2026-07-21", percentComplete: 0, dependencyIds: ["hv-activity-6"], status: "queued" },
      { label: "MEP rough-in start", crew: "Trades", start: "2026-07-24", end: "2026-08-10", percentComplete: 0, dependencyIds: ["hv-activity-7"], status: "queued" },
    ]),
  },
  {
    id: "birch-lane",
    name: "42 Birch Lane",
    address: "42 Birch Lane, Naperville, IL",
    projectType: "Remodel",
    homeownerName: "The Carters",
    lat: 41.7508,
    lng: -88.1535,
    phase: "Drywall / Finish",
    percentComplete: 73,
    contractValue: 486000,
    personaAccess: ["Foreman", "Superintendent", "Homeowner", "Office / PM"],
    milestones: [
      { id: "bl-ms-1", label: "Demo complete", date: "2026-03-07", status: "done" },
      { id: "bl-ms-2", label: "Drywall progress review", date: "2026-07-13", status: "at-risk" },
      { id: "bl-ms-3", label: "Electrical trim", date: "2026-07-18", status: "upcoming" },
      { id: "bl-ms-4", label: "Cabinet install", date: "2026-07-29", status: "upcoming" },
    ],
    activities: makeActivities("bl", [
      { label: "Drywall hang", crew: "Drywall crew", start: "2026-07-07", end: "2026-07-11", percentComplete: 100, dependencyIds: [], status: "complete" },
      { label: "Drywall tape and mud", crew: "Drywall crew", start: "2026-07-11", end: "2026-07-15", percentComplete: 80, dependencyIds: ["bl-activity-1"], status: "at-risk" },
      { label: "Inspection request", crew: "Superintendent", start: "2026-07-14", end: "2026-07-14", percentComplete: 0, dependencyIds: ["bl-activity-2"], status: "blocked" },
      { label: "Electrical trim", crew: "Electrician", start: "2026-07-18", end: "2026-07-19", percentComplete: 0, dependencyIds: ["bl-activity-3"], status: "blocked" },
      { label: "Prime walls", crew: "Painter", start: "2026-07-20", end: "2026-07-21", percentComplete: 0, dependencyIds: ["bl-activity-4"], status: "queued" },
      { label: "Cabinet template confirmation", crew: "Cabinet supplier", start: "2026-07-21", end: "2026-07-21", percentComplete: 0, dependencyIds: ["bl-activity-4"], status: "queued" },
      { label: "Cabinet install", crew: "Millwork", start: "2026-07-29", end: "2026-07-30", percentComplete: 0, dependencyIds: ["bl-activity-6"], status: "queued" },
      { label: "Final fixture punch", crew: "PM", start: "2026-08-04", end: "2026-08-04", percentComplete: 0, dependencyIds: ["bl-activity-7"], status: "queued" },
    ]),
  },
  {
    id: "commerce-park",
    name: "210 Commerce Park",
    address: "210 Commerce Park, Austin, TX",
    projectType: "Light commercial TI",
    lat: 30.2572,
    lng: -97.7428,
    phase: "Closeout",
    percentComplete: 91,
    contractValue: 935000,
    personaAccess: ["Superintendent", "Office / PM"],
    milestones: [
      { id: "cp-ms-1", label: "MEP complete", date: "2026-05-29", status: "done" },
      { id: "cp-ms-2", label: "Final walkthrough", date: "2026-07-15", status: "current" },
      { id: "cp-ms-3", label: "Punch closeout", date: "2026-07-24", status: "upcoming" },
      { id: "cp-ms-4", label: "Turnover package", date: "2026-07-28", status: "upcoming" },
    ],
    activities: makeActivities("cp", [
      { label: "Owner punch walk", crew: "Builder / GC", start: "2026-07-12", end: "2026-07-12", percentComplete: 0, dependencyIds: [], status: "active" },
      { label: "Paint touch-ups", crew: "Painter", start: "2026-07-13", end: "2026-07-14", percentComplete: 0, dependencyIds: ["cp-activity-1"], status: "queued" },
      { label: "Ceiling tile replacement", crew: "Ceiling crew", start: "2026-07-13", end: "2026-07-14", percentComplete: 0, dependencyIds: ["cp-activity-1"], status: "queued" },
      { label: "Fire alarm final", crew: "Fire alarm", start: "2026-07-16", end: "2026-07-16", percentComplete: 0, dependencyIds: ["cp-activity-2", "cp-activity-3"], status: "queued" },
      { label: "Closeout docs assembly", crew: "Office / PM", start: "2026-07-16", end: "2026-07-24", percentComplete: 40, dependencyIds: [], status: "active" },
      { label: "Client training", crew: "Builder / GC", start: "2026-07-25", end: "2026-07-25", percentComplete: 0, dependencyIds: ["cp-activity-4", "cp-activity-5"], status: "queued" },
      { label: "Final turnover", crew: "Builder / GC", start: "2026-07-28", end: "2026-07-28", percentComplete: 0, dependencyIds: ["cp-activity-6"], status: "queued" },
      { label: "Warranty kickoff", crew: "Office / PM", start: "2026-07-30", end: "2026-07-30", percentComplete: 0, dependencyIds: ["cp-activity-7"], status: "queued" },
    ]),
  },
];

const contacts: Contact[] = [
  { id: "c1", name: "Marco Silva", role: "Foreman", company: "FieldFirst Demo", phone: "(312) 555-0101", email: "marco@fieldfirst.dev", projectIds: ["harbor-view", "birch-lane"], communicationPolicy: policyMatrix.foreman },
  { id: "c2", name: "Dana Wells", role: "Superintendent", company: "FieldFirst Demo", phone: "(312) 555-0102", email: "dana@fieldfirst.dev", projectIds: ["harbor-view", "birch-lane", "commerce-park"], communicationPolicy: policyMatrix.superintendent },
  { id: "c3", name: "Lena Henderson", role: "Homeowner", company: "Henderson Family", phone: "(262) 555-0103", email: "hendersons@example.com", projectIds: ["harbor-view"], communicationPolicy: policyMatrix.homeowner },
  { id: "c4", name: "Chris Carter", role: "Homeowner", company: "Carter Family", phone: "(630) 555-0104", email: "carters@example.com", projectIds: ["birch-lane"], communicationPolicy: policyMatrix.homeowner },
  { id: "c5", name: "Reese Morgan", role: "Office / PM", company: "FieldFirst Demo", phone: "(512) 555-0105", email: "reese@fieldfirst.dev", projectIds: ["harbor-view", "birch-lane", "commerce-park"], communicationPolicy: policyMatrix.builder },
  { id: "c6", name: "Isaac Rowe", role: "Builder / GC", company: "Rowe Builders", phone: "(512) 555-0106", email: "isaac@rowebuilders.com", projectIds: ["commerce-park"], communicationPolicy: policyMatrix.builder },
  { id: "c7", name: "Tara Hsu", role: "Supplier", company: "Summit Supply", phone: "(847) 555-0107", email: "tara@summitsupply.com", projectIds: ["harbor-view", "birch-lane"], communicationPolicy: policyMatrix.supplier },
  { id: "c8", name: "Luis Vega", role: "Subcontractor", company: "Vega Drywall", phone: "(630) 555-0108", email: "luis@vegadrywall.com", projectIds: ["birch-lane"], communicationPolicy: policyMatrix.subcontractor },
  { id: "c9", name: "Priya Shah", role: "Architect / Engineer", company: "Axis Studio", phone: "(773) 555-0109", email: "priya@axisstudio.com", projectIds: ["harbor-view"], communicationPolicy: policyMatrix.architect },
  { id: "c10", name: "Mason Price", role: "Architect / Engineer", company: "Parkline MEP", phone: "(512) 555-0110", email: "mason@parklinemep.com", projectIds: ["commerce-park"], communicationPolicy: policyMatrix.architect },
];

const photoAssets: PhotoAsset[] = [
  { id: "photo-framing-1", label: "Framing progress", src: "/demo/framing-progress.svg", classification: "progress" },
  { id: "photo-framing-2", label: "Window mismatch", src: "/demo/window-conflict.svg", classification: "design conflict" },
  { id: "photo-hazard-1", label: "Open stair edge", src: "/demo/open-edge-hazard.svg", classification: "safety hazard" },
  { id: "photo-delivery-1", label: "Roof truss delivery", src: "/demo/truss-delivery.svg", classification: "delivery" },
  { id: "photo-drywall-1", label: "Drywall progress", src: "/demo/drywall-progress.svg", classification: "progress" },
  { id: "photo-drywall-2", label: "Water damage", src: "/demo/water-damage.svg", classification: "damage" },
  { id: "photo-doc-1", label: "Permit documentation", src: "/demo/documentation-board.svg", classification: "documentation" },
  { id: "photo-warranty-1", label: "Cabinet scratch", src: "/demo/cabinet-warranty.svg", classification: "warranty" },
  { id: "photo-delivery-2", label: "Pallet staging", src: "/demo/pallet-staging.svg", classification: "delivery" },
  { id: "photo-hazard-2", label: "Trip hazard cord", src: "/demo/trip-hazard.svg", classification: "safety hazard" },
];

const captureEvents: CaptureEvent[] = [
  {
    id: "capture-1",
    projectId: "harbor-view",
    createdAt: "2026-07-12T07:42:00.000Z",
    createdBy: "Foreman",
    classification: "progress",
    area: "West wall framing",
    summary: "Framing closed out on west wall before weather moved in.",
    severity: "FYI",
    visibilityLevel: 2,
    syncState: "Verified on server",
    photoIds: ["photo-framing-1"],
    routeRuleIds: ["rule-progress-daily-log"],
    actionSummary: ["Attached to daily log", "Shared with superintendent"],
  },
  {
    id: "capture-2",
    projectId: "harbor-view",
    createdAt: "2026-07-12T08:11:00.000Z",
    createdBy: "Foreman",
    classification: "design conflict",
    area: "Window openings",
    summary: "Openings do not match latest plan revision A5.4.",
    severity: "Approval required",
    visibilityLevel: 1,
    syncState: "Uploading",
    photoIds: ["photo-framing-2"],
    routeRuleIds: ["rule-design-rfi"],
    actionSummary: ["Drafted RFI", "Held homeowner update pending approval"],
  },
  {
    id: "capture-3",
    projectId: "birch-lane",
    createdAt: "2026-07-11T20:16:00.000Z",
    createdBy: "Foreman",
    classification: "safety hazard",
    area: "Hallway transition",
    summary: "Temporary power cord crosses walkway without cover.",
    severity: "Safety critical",
    visibilityLevel: 1,
    syncState: "Upload failed - retrying",
    photoIds: ["photo-hazard-2"],
    routeRuleIds: ["rule-safety-escalation"],
    actionSummary: ["Notified superintendent", "Started acknowledgement timer"],
  },
];

const notifications: Notification[] = [
  {
    id: "note-1",
    projectId: "birch-lane",
    createdAt: "2026-07-12T08:30:00.000Z",
    title: "Safety acknowledgement overdue",
    body: "Trip hazard remains unacknowledged for 14 minutes. Escalation will trigger automatically.",
    severity: "Safety critical",
    status: "pending",
    recipientRoles: ["Superintendent", "Office / PM"],
    visibilityLevel: 1,
    routeReason: "Rule safety-escalation requires immediate acknowledgement.",
    ackRequired: true,
    escalatesAt: "2026-07-12T08:44:00.000Z",
  },
  {
    id: "note-2",
    projectId: "harbor-view",
    createdAt: "2026-07-12T09:00:00.000Z",
    title: "Window opening conflict held for review",
    body: "Potential design conflict queued for superintendent approval before any client-facing update.",
    severity: "Approval required",
    status: "sent",
    recipientRoles: ["Superintendent", "Architect / Engineer"],
    visibilityLevel: 1,
    routeReason: "Rule design-rfi holds external communication until validated.",
    ackRequired: false,
  },
];

const tasks: Task[] = [
  { id: "task-1", projectId: "harbor-view", title: "Verify west wall window dimensions", type: "task", status: "open", assignedTo: "Superintendent", dueDate: "2026-07-12", evidenceRequired: true, evidencePhotoIds: [], summary: "Need photo and tape measure confirmation against revision A5.4." },
  { id: "task-2", projectId: "birch-lane", title: "Remove hallway trip hazard", type: "punch", status: "blocked", assignedTo: "Foreman", dueDate: "2026-07-12", evidenceRequired: true, evidencePhotoIds: [], summary: "Completion blocked until corrected condition is captured." },
  { id: "task-3", projectId: "birch-lane", title: "Confirm drywall inspection date", type: "task", status: "open", assignedTo: "Superintendent", dueDate: "2026-07-13", evidenceRequired: false, evidencePhotoIds: [], summary: "Need alternate slots before electrical trim slips." },
  { id: "task-4", projectId: "harbor-view", title: "Draft homeowner weekly update", type: "task", status: "in-progress", assignedTo: "Office / PM", dueDate: "2026-07-12", evidenceRequired: false, evidencePhotoIds: [], summary: "Hold plumbing schedule language until superintendent confirms impact." },
  { id: "task-5", projectId: "commerce-park", title: "Upload as-built turnover set", type: "task", status: "in-progress", assignedTo: "Office / PM", dueDate: "2026-07-24", evidenceRequired: false, evidencePhotoIds: [], summary: "Need architect stamp before owner share." },
  { id: "task-6", projectId: "harbor-view", title: "Approve framing revision RFI", type: "approval", status: "open", assignedTo: "Architect / Engineer", dueDate: "2026-07-13", evidenceRequired: false, evidencePhotoIds: [], summary: "Architect response required before framing continues in affected bay." },
];

const dailyLogs: DailyLog[] = [
  {
    id: "log-1",
    projectId: "harbor-view",
    date: "2026-07-12",
    weather: "74F, light lake wind, dry",
    workforce: [
      { role: "Framers", count: 3, hours: 25.5 },
      { role: "Superintendent", count: 1, hours: 4 },
    ],
    workPerformed: ["Finished west wall framing", "Staged roof truss laydown area"],
    delays: ["Pending window opening clarification"],
    visitors: ["Axis Studio architect site walk"],
    photoIds: ["photo-framing-1", "photo-framing-2"],
    captureEventIds: ["capture-1", "capture-2"],
  },
  {
    id: "log-2",
    projectId: "birch-lane",
    date: "2026-07-11",
    weather: "81F, humid",
    workforce: [{ role: "Drywall crew", count: 4, hours: 34 }],
    workPerformed: ["Mud and tape at kitchen and hall", "Protected finished floors"],
    delays: ["Power-cord hazard required immediate correction"],
    visitors: ["Homeowner walk-through"],
    photoIds: ["photo-drywall-1", "photo-hazard-2"],
    captureEventIds: ["capture-3"],
  },
  {
    id: "log-3",
    projectId: "birch-lane",
    date: "2026-07-10",
    weather: "79F, clear",
    workforce: [{ role: "Drywall crew", count: 5, hours: 41 }],
    workPerformed: ["Drywall hang complete in primary suite and hall"],
    delays: [],
    visitors: [],
    photoIds: ["photo-drywall-1"],
    captureEventIds: [],
  },
  {
    id: "log-4",
    projectId: "commerce-park",
    date: "2026-07-09",
    weather: "95F, partly cloudy",
    workforce: [{ role: "Closeout team", count: 2, hours: 16 }],
    workPerformed: ["Compiled O&M manuals", "Updated punch list room tags"],
    delays: ["Awaiting owner training date"],
    visitors: ["Fire alarm vendor"],
    photoIds: ["photo-doc-1"],
    captureEventIds: [],
  },
  {
    id: "log-5",
    projectId: "harbor-view",
    date: "2026-07-09",
    weather: "69F, overcast",
    workforce: [{ role: "Concrete", count: 2, hours: 18 }],
    workPerformed: ["Garage slab cure check", "Material delivery coordination"],
    delays: [],
    visitors: ["Roof truss supplier"],
    photoIds: ["photo-delivery-1"],
    captureEventIds: [],
  },
];

const rules: Rule[] = [
  {
    id: "rule-progress-daily-log",
    name: "Progress capture to daily log",
    trigger: "When classification = progress",
    conditions: ["Project is recognized", "Visibility not homeowner-friendly by default"],
    actions: [
      { type: "attach", target: "daily log", description: "Attach photos to today’s log." },
      { type: "notify", target: "superintendent", description: "Send progress summary to superintendent." },
    ],
    controlLevel: "automatic with undo",
    enabled: true,
    summary: "Progress captures auto-file to the daily log and notify the superintendent.",
  },
  {
    id: "rule-design-rfi",
    name: "Design conflict to RFI",
    trigger: "When classification = design conflict",
    conditions: ["Potential drawing mismatch", "External update not yet approved"],
    actions: [
      { type: "draft", target: "RFI", description: "Draft an RFI with photo evidence." },
      { type: "hold", target: "homeowner updates", description: "Hold homeowner-facing note until review." },
      { type: "notify", target: "architect + superintendent", description: "Route conflict summary internally." },
    ],
    controlLevel: "recommendation requiring approval",
    enabled: true,
    summary: "Design conflicts become RFI drafts and hold client communication until approved.",
  },
  {
    id: "rule-safety-escalation",
    name: "Safety escalation",
    trigger: "When classification = safety hazard",
    conditions: ["Hazard is unresolved", "Acknowledgement absent after timer"],
    actions: [
      { type: "notify", target: "superintendent", description: "Send immediate safety alert." },
      { type: "start timer", target: "30 second escalation", description: "Start acknowledgement timer." },
      { type: "escalate", target: "office / PM", description: "Escalate when timer expires." },
    ],
    controlLevel: "mandatory human approval",
    enabled: true,
    summary: "Safety items notify immediately and escalate if unacknowledged.",
  },
];

const auditTrail: AuditEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-07-11T20:16:04.000Z",
    projectId: "birch-lane",
    actor: "FieldFirst mock engine",
    action: "Matched hazard capture to Birch Lane hallway transition",
    why: "GPS signal, active drywall schedule, and recent foreman visits aligned.",
    ruleId: "rule-safety-escalation",
    controlLevel: "automatic",
    visibilityLevel: 1,
  },
  {
    id: "audit-2",
    timestamp: "2026-07-11T20:16:08.000Z",
    projectId: "birch-lane",
    actor: "FieldFirst mock engine",
    action: "Notified superintendent and started acknowledgement timer",
    why: "Safety hazard carries mandatory human approval before closure.",
    ruleId: "rule-safety-escalation",
    controlLevel: "mandatory human approval",
    visibilityLevel: 1,
  },
  {
    id: "audit-3",
    timestamp: "2026-07-12T08:11:06.000Z",
    projectId: "harbor-view",
    actor: "FieldFirst mock engine",
    action: "Drafted RFI-204 for window opening conflict",
    why: "Photo evidence matched deterministic design conflict set.",
    ruleId: "rule-design-rfi",
    controlLevel: "recommendation requiring approval",
    visibilityLevel: 1,
  },
  {
    id: "audit-4",
    timestamp: "2026-07-12T08:11:10.000Z",
    projectId: "harbor-view",
    actor: "Dana Wells",
    action: "Held homeowner update pending superintendent review",
    why: "Client-sensitive language requires validation before release.",
    ruleId: "rule-design-rfi",
    controlLevel: "mandatory human approval",
    visibilityLevel: 1,
  },
];

const rfiDrafts: RfiDraft[] = [
  {
    id: "rfi-1",
    projectId: "harbor-view",
    number: "RFI-204",
    question: "Window openings at west wall do not match revision A5.4. Confirm rough opening dimensions before roof framing proceeds.",
    drawingRef: "A5.4 / S2.1",
    ballInCourt: "Axis Studio",
    dueDate: "2026-07-13",
  },
];

const threads: MessageThread[] = [
  {
    id: "thread-1",
    projectId: "harbor-view",
    audience: "homeowner",
    title: "Weekly homeowner update",
    messages: [
      {
        id: "msg-1",
        sender: "Office / PM",
        sentAt: "2026-07-10T17:02:00.000Z",
        body: "Framing continues to move well. We are coordinating a sequencing adjustment before cabinet-installation milestones are affected.",
        readBy: ["Lena Henderson"],
      },
    ],
  },
  {
    id: "thread-2",
    projectId: "harbor-view",
    audience: "internal",
    title: "Plumbing schedule risk",
    messages: [
      {
        id: "msg-2",
        sender: "Foreman",
        sentAt: "2026-07-11T16:08:00.000Z",
        body: "Plumber no-show. Rescheduling may affect cabinet installation.",
        readBy: ["Dana Wells", "Reese Morgan"],
      },
    ],
  },
];

export const seedState: DemoState = {
  currentPersona: "Foreman",
  selectedProjectId: "harbor-view",
  projects,
  contacts,
  photoAssets,
  captureEvents,
  notifications,
  tasks,
  dailyLogs,
  rules,
  auditTrail,
  rfiDrafts,
  threads,
  voiceDecisionTrace: [],
  lastVoiceTranscript: "",
  offlineMode: false,
};

export function cloneSeedState(): DemoState {
  return JSON.parse(JSON.stringify(seedState)) as DemoState;
}
